name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest  # Using GitHub-hosted Ubuntu Runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

   
  cd:
    name: Continuous Deployment
    runs-on: self-hosted 
    needs: ci  

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      run: |
        sudo apt-get update && sudo apt-get install -y awscli
        aws configure set aws_access_key_id AKIATCKARAOGGBGMAXQT
        aws configure set aws_secret_access_key 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
        aws configure set default.region us-east-1

    - name: Authenticate with AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 211125601164.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Docker Image to ECR
      run: |
        docker build -t ml-pipeline .
        docker tag ml-pipeline:latest 211125601164.dkr.ecr.us-east-1.amazonaws.com/ml-pipeline:latest
        docker push 211125601164.dkr.ecr.us-east-1.amazonaws.com/ml-pipeline:latest

    - name: Deploy to AWS EC2
      run: |
        docker pull 211125601164.dkr.ecr.us-east-1.amazonaws.com/ml-pipeline:latest
        docker stop $(docker ps -aq) || true
        docker run -d -p 8000:8000 211125601164.dkr.ecr.us-east-1.amazonaws.com/ml-pipeline:latest
